### PR TITLE
Document: Update LoongArch SMBIOS specification

### PR DESCRIPTION
**Pull request by kilaterlee**
1. Add chapter numbers to each section.
2. Add Standard Processor Additonal Information and standard Processor-specific Block.
3. Modified the LoongArch Processor-specific Block Structure, adding Revision and Block
    Length fields.

Signed-off-by: Chao Li <lichao@loongson.cn>

### CODE REVIEW

**Comment by kilaterlee** [comment]
@qiandongyan @xen0n @yetist @EricGao2015 @kimonberlin
Please review this patch.

Thanks,
Chao Li

**Comment by xen0n** [comment]
冲突了，rebase 下。。应该在当前最新提交基础上修改而不是从头再提交一遍

**Comment by kilaterlee** [comment]
我已经拉取最新的了啊

**Comment by kilaterlee** [comment]
> 冲突了，rebase 下。。应该在当前最新提交基础上修改而不是从头再提交一遍

这次好了

**Comment by yetist** [comment]
SMBIOS 是这个吧？https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.5.0.pdf

我觉得你的编号应该以当前最新 SMBIOS 为准呀，这样可以方便看出来，你哪一部分内容，将会插入到 spec 那个章节中去。

**Comment by yetist** [comment]
另外，7.5.2，Table 23是不是也应该加东西？

**Comment by kilaterlee** [comment]
> SMBIOS 是这个吧？https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.5.0.pdf
> 
> 我觉得你的编号应该以当前最新 SMBIOS 为准呀，这样可以方便看出来，你哪一部分内容，将会插入到 spec 那个章节中去。

SMBIOS规范是你那个链接的。

这个文档以Type 44的补充形式存在的，这个章节编号是本地的，跟SMBIOS规范的章节没关系。

**Comment by kilaterlee** [comment]
> 另外，7.5.2，Table 23是不是也应该加东西？

已经加了，我已经提CR给DMTF group了

**Review by qiandongyan — APPROVED** [review]

**Review by yetist — APPROVED** [review]
LGTM

**Comment by kilaterlee** [comment]
@peterwangjw @90geek  Please review

**Comment by kimonberlin** [comment]
In section 3.3, the block length should be 28h, not 27h.

**Comment by xen0n** [comment]
Not directly relevant, but why the table "3.3 LoongArch Processor-specific Block Structure" has the Reserved field set to have "varied" value? IMO such fields should be forced to have sensible (e.g. zero) values for proper forward compatibility. See for example the Table 105 – System Boot Information (Type 32) structure in the SMBIOS 3.5.0 spec.

**Comment by xen0n** [comment]
Also I think the section 7.5 Processor Information (Type 4) should be amended as well; you may already have tweaked this section separately in your upstream submission, and I'm just confirming.

**Comment by kimonberlin** [comment]
> Not directly relevant, but why the table "3.3 LoongArch Processor-specific Block Structure" has the Reserved field set to have "varied" value? IMO such fields should be forced to have sensible (e.g. zero) values for proper forward compatibility. See for example the Table 105 – System Boot Information (Type 32) structure in the SMBIOS 3.5.0 spec.

I agree. This should be 0 for now.

**Comment by kilaterlee** [comment]
> > Not directly relevant, but why the table "3.3 LoongArch Processor-specific Block Structure" has the Reserved field set to have "varied" value? IMO such fields should be forced to have sensible (e.g. zero) values for proper forward compatibility. See for example the Table 105 – System Boot Information (Type 32) structure in the SMBIOS 3.5.0 spec.
> 
> I agree. This should be 0 for now.

Okay, I have updated this field.

**Review by xen0n — APPROVED** [review]
Seems good to me.

**Comment by kilaterlee** [comment]
@FreeFlyingSheep If Kimon has no other questions, please approve and merge, thanks.

**Comment by xen0n** [comment]
Yeah let's just wait a moment (due to timezone) before merging.

**Review by FreeFlyingSheep — APPROVED** [review]

**Pull request merged**
